#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-shellinabox-update';

# templates to expand
foreach my $event (qw ( nethserver-shellinabox-update nethserver-shellinabox-save)) {
    templates2events("/etc/sysconfig/shellinaboxd", $event);
    templates2events('/etc/httpd/conf.d/shellinabox.conf', $event);
}

# services to launch on event
foreach my $event (qw ( nethserver-shellinabox-update nethserver-shellinabox-save)) {
event_services($event,
    'httpd' => 'reload');
}

# actions to do
my $event = 'nethserver-shellinabox-update';
event_actions($event, 
             'initialize-default-databases' => '00',
             'nethserver-shellinabox-service-conf' => '99');


#my $event = 'nethserver-shellinabox-save';
#event_actions($event,
#'nethserver-shellinabox-service-conf' => '99');

exit;
