#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-shellinabox-update';

# templates to expand
foreach my $event (qw ( 
    nethserver-openssh-save 
    nethserver-openssh-update 
    nethserver-shellinabox-update 
    nethserver-shellinabox-save)) {
        templates2events("/etc/sysconfig/shellinaboxd", $event);
        templates2events('/etc/httpd/admin-conf.d/shellinabox.conf', $event);
    }

# services to launch on event
foreach my $event (qw ( 
    nethserver-openssh-save 
    nethserver-openssh-update
    nethserver-shellinabox-update 
    nethserver-shellinabox-save)) {
        event_services($event, 'shellinaboxd'=> 'restart');
    }

# actions to do
my $event = 'nethserver-shellinabox-update';
event_actions($event, 
             'initialize-default-databases' => '00',
             'nethserver-shellinabox-RandomUrl' => '01',
             'nethserver-httpd-admin-asyncreload' => '99');

my $event = 'nethserver-shellinabox-save';
event_actions($event,
             'nethserver-shellinabox-RandomUrl' => '01',
             'runlevel-adjust' => '70',
             'firewall-adjust' => '95',
             'nethserver-httpd-admin-asyncreload' => '99');

my $event = 'trusted-networks-modify';
    templates2events('/etc/httpd/admin-conf.d/shellinabox.conf', $event);
event_actions($event,
             'nethserver-httpd-admin-asyncreload' => '99');

