#!/usr/bin/perl -w

use esmith::ConfigDB;
my $db = esmith::ConfigDB->open_ro;
my $status = $db->get_prop('shellinaboxd','status')|| 'disabled';

if ($status eq 'enabled') {
system ('/sbin/service shellinaboxd restart');
}

else {
system ('/sbin/service shellinaboxd stop');
}
system ('/sbin/e-smith/signal-event runlevel-adjust');
system ('/sbin/e-smith/signal-event firewall-adjust');
